# Generated by Django 2.2 on 2020-05-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeADifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(default='', max_length=100)),
                ('donation_cover', models.ImageField(default='', upload_to='MakeADifference')),
                ('description', models.TextField(default='')),
                ('contact_details', models.TextField(default='')),
            ],
        ),
    ]
