# Generated by Django 2.2 on 2020-06-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
