# Generated by Django 2.2 on 2020-06-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200602_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='whatsapp',
            field=models.BigIntegerField(default='0'),
        ),
    ]
