# Generated by Django 2.2 on 2020-06-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200602_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
