# Generated by Django 2.2 on 2020-06-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200602_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaildata',
            name='email',
        ),
    ]
