# Generated by Django 2.2.14 on 2020-07-22 13:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_emaildata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9999999999', max_length=128, region=None),
        ),
    ]
