# Generated by Django 2.2.14 on 2020-07-23 06:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200722_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
