# Generated by Django 2.2 on 2020-06-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stall_city',
        ),
    ]
