# Generated by Django 2.2.14 on 2020-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_makevisible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('testi', models.CharField(default='', max_length=300)),
                ('testi_image', models.ImageField(default='', upload_to='testimonials')),
            ],
        ),
    ]
