# Generated by Django 2.2.14 on 2020-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='make_visible',
            field=models.BooleanField(default=False),
        ),
    ]
