# Generated by Django 2.2.14 on 2020-09-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonials_make_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='testi',
            field=models.CharField(default='', max_length=500),
        ),
    ]
