# Generated by Django 2.2 on 2020-05-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stall_frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('cover', models.ImageField(default='', upload_to='coverimages')),
                ('description', models.TextField(default='')),
                ('contact_stall', models.TextField(default='')),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='stall_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='', upload_to='products_images')),
                ('category', models.CharField(default='', max_length=30)),
                ('stall_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stalls.stall_frame')),
            ],
        ),
    ]
