# Generated by Django 2.2 on 2020-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='poweredby',
            field=models.BooleanField(default=False),
        ),
    ]
