# Generated by Django 2.2 on 2020-06-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0002_stall_frame_poweredby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall_frame',
            old_name='poweredby',
            new_name='poweredby_stall',
        ),
    ]
