# Generated by Django 2.2 on 2020-06-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0003_auto_20200603_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall_frame',
            old_name='poweredby_stall',
            new_name='poweredby',
        ),
    ]
