# Generated by Django 2.2 on 2020-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0004_auto_20200603_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall_frame',
            name='poweredby',
        ),
        migrations.AddField(
            model_name='stall_frame',
            name='poweredby_stall',
            field=models.BooleanField(default=False),
        ),
    ]
