# Generated by Django 2.2 on 2020-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0005_auto_20200603_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='city',
            field=models.CharField(default='Chennai', max_length=100),
        ),
    ]
