# Generated by Django 2.2 on 2020-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0006_stall_frame_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stall_frame',
            name='city',
        ),
    ]
