# Generated by Django 2.2 on 2020-06-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0008_auto_20200608_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stalls.stall_city'),
        ),
    ]
