# Generated by Django 2.2 on 2020-06-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0009_stall_frame_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='stall_products',
            name='category',
        ),
    ]
