# Generated by Django 2.2 on 2020-06-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0010_auto_20200608_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_products',
            name='choose_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stalls.product_category'),
        ),
    ]
