# Generated by Django 2.2 on 2020-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0012_auto_20200609_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_city',
            name='city_image',
            field=models.ImageField(default='', upload_to='City_images'),
        ),
    ]
