# Generated by Django 2.2 on 2020-06-24 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stalls', '0013_stall_city_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='stall_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
