# Generated by Django 2.2 on 2020-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0017_auto_20200625_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='contact_stall',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='stall_frame',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
