# Generated by Django 2.2 on 2020-06-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0018_auto_20200627_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='stall_visible_on_website',
            field=models.BooleanField(default=False),
        ),
    ]
