# Generated by Django 2.2.14 on 2020-07-21 16:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0019_stall_frame_stall_visible_on_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9999999999', max_length=128, region=None),
        ),
    ]
