# Generated by Django 2.2.14 on 2020-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0020_stall_frame_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
