# Generated by Django 2.2.14 on 2020-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0021_auto_20200722_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
