# Generated by Django 2.2.14 on 2020-07-23 07:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0022_auto_20200723_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='stall_frame',
            name='cover',
            field=models.ImageField(upload_to='newcoverimages'),
        ),
    ]
