# Generated by Django 2.2.14 on 2020-07-23 08:09

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0026_auto_20200723_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='cover',
            field=image_optimizer.fields.OptimizedImageField(upload_to='coverimages'),
        ),
        migrations.AlterField(
            model_name='stall_products',
            name='product_image',
            field=image_optimizer.fields.OptimizedImageField(upload_to='products_images'),
        ),
    ]
