# Generated by Django 2.2.14 on 2020-07-23 08:51

from django.db import migrations
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0028_auto_20200723_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='cover',
            field=optimized_image.fields.OptimizedImageField(upload_to='newcoverimages'),
        ),
        migrations.AlterField(
            model_name='stall_products',
            name='product_image',
            field=optimized_image.fields.OptimizedImageField(upload_to='products_images'),
        ),
    ]
