# Generated by Django 2.2.14 on 2020-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0030_auto_20200723_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='cover',
            field=models.ImageField(default='', upload_to='coverimages'),
        ),
    ]
