# Generated by Django 2.2.14 on 2020-07-23 09:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0031_auto_20200723_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='contact_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9999999999', max_length=128, region=None),
        ),
    ]
