# Generated by Django 2.2.14 on 2020-08-26 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0039_auto_20200826_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Datetest',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
