# Generated by Django 2.2.14 on 2020-08-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0040_article_datetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Datetest',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
