# Generated by Django 2.2.14 on 2020-08-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0041_auto_20200827_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='position',
            field=models.IntegerField(default=500),
        ),
    ]
