# Generated by Django 2.2.14 on 2020-08-29 14:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0042_stall_frame_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
        ),
    ]
