# Generated by Django 2.2.14 on 2020-08-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0043_stall_frame_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_frame',
            name='second_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_category', to='stalls.product_category'),
        ),
        migrations.AddField(
            model_name='stall_frame',
            name='third_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='third_category', to='stalls.product_category'),
        ),
        migrations.AlterField(
            model_name='stall_frame',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='stalls.product_category'),
        ),
    ]
