# Generated by Django 2.2.14 on 2020-09-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0045_auto_20200901_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_products',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
