# Generated by Django 2.2.14 on 2020-12-22 15:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0046_stall_products_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall_products',
            name='weblink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title'),
        ),
    ]
