# Generated by Django 2.2.14 on 2020-12-22 15:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0047_auto_20201222_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_frame',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name'),
        ),
    ]
