# Generated by Django 2.2.14 on 2020-12-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0048_auto_20201222_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall_products',
            name='weblink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
